openapi: 3.1.0
info:
  title: OpensShift Pod API Wrapper
  description: A sample API to illustrate OpenAPI specification
  version: 1.0.0
servers:
  - url: https://api.sample.com/v1
paths:
  /optimize:
    patch:
      summary: Get a list of users
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  